### ISSUE TITLE
Example app fails during to first building com/android/build/api/variant/ScopedArtifacts$Scope`

### ISSUE THREAD

**Issue by oguzydz** [newrelic/newrelic-react-native-agent#125]
React-Native-Test-App fails when building in my local, I came this issue from when I want to add the New Relic for my exisiting project. I am getting same error with the example test app. 

## Description

Actually, I can just support the terminal log when I want to build the example app also my existing app. 

## Expected Behavior

I want to expect when I initally want to setup the new relic no getting error. 

## Relevant Logs / Console output

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com/android/build/api/variant/ScopedArtifacts$Scope`

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

> 192:React-Native-Test-App oguzyildiz$ npx react-native info
> info Fetching system and libraries information...
> System:
>     OS: macOS 13.4.1
>     CPU: (10) arm64 Apple M2 Pro
>     Memory: 114.88 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 18.16.0 - /usr/local/bin/node
>     Yarn: 1.22.17 - /usr/local/bin/yarn
>     npm: 9.6.7 - /usr/local/bin/npm
>     Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
>   Managers:
>     CocoaPods: 1.12.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
>     Android SDK:
>       API Levels: 28, 29, 30, 31, 33
>       Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
>       System Images: android-26 | ARM 64 v8a, android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 2022.2 AI-222.4459.24.2221.9862592
>     Xcode: 14.3/14E222b - /usr/bin/xcodebuild
>   Languages:
>     Java: 11.0.11 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 18.2.0 => 18.2.0 
>     react-native: 0.71.10 => 0.71.10 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> 192:React-Native-Test-App oguzyildiz$

**Comment by vikrant-k-simformsolutions** [comment]
@ndesai-newrelic @kennyt276 I'm encountering a similar issue with React Native version ^0.72.3. The problem seems to arise when we update the classpath to `"com.newrelic.agent.android:agent-gradle-plugin:7.0.0"` from `"com.newrelic.agent.android:agent-gradle-plugin:6.11.1"`. It triggers an error: "Failed to notify project evaluation listener. > com/android/build/api/variant/ScopedArtifacts$Scope."

As a workaround, you can temporarily resolve this by downgrading the version of the agent-gradle-plugin to 6.11.1:

`classpath "com.newrelic.agent.android:agent-gradle-plugin:6.11.1"`

This should get you past the error until a more permanent solution is available. 

@oguzydz, you might find this temporary fix helpful.

**Comment by ndesai-newrelic** [comment]
@vikrant-k-simformsolutions @oguzydz  The issue is related to the Android tools version. To resolve it, please update the Android tools from version 7.3.1 to 7.4.2 on this line: https://github.com/newrelic/newrelic-react-native-agent/blob/870e135095aed34aef95a99329c2329256b95287/NewRelicExampleApp/React-Native-Test-App/android/build.gradle#L18. This should fix the problem, and we will include this update in our next release.

**Comment by oguzydz** [comment]
hey @ndesai-newrelic I changed to Android tools from version 7.3.1 to 7.4.2.

I got this error on line:
`error: package com.newrelic does not exist
import com.newrelic.NRMModularAgentPackage;`

<img width="1119" alt="Screenshot 2023-09-05 at 8 34 47 PM" src="https://github.com/newrelic/newrelic-react-native-agent/assets/36233491/84784296-e73f-4971-ac12-b69cd8161433">

**Comment by ndesai-newrelic** [comment]
@oguzydz which version of react native are you using?

**Comment by ndesai-newrelic** [comment]
the issue is on react native side,please refer this issue, https://github.com/newrelic/newrelic-react-native-agent/issues/124#issuecomment-1706695946

**Comment by oguzydz** [comment]
Okay, thanks!
