### ISSUE TITLE
Doesn't seem to work with Hermes at all

### ISSUE THREAD

**Issue by jkester1986** [newrelic/newrelic-react-native-agent#75]
This package doesn't seem to work with Hermes at all. Here's the steps I took:

1. Created an error that causes an app crash (I just threw text inside the return statement of a component, not wrapped in a <Text>)
2. Confirm error gets logged when Hermes is **off**
3. Try to reproduce after turning Hermes on, without success. Nothing ends up on the NR logs

**Comment by kthai-nr** [comment]
Hello, I am able to record errors and report data with Hermes enabled on my end. My configuration is as follows:
android/app/build.gradle
```
project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
]
```
ios/Podfile
```
:hermes_enabled => true,
```
All data is reporting with hermes enabled. 

Are you having troubles with both Android and iOS? We might need some additional information in order to reproduce this issue:
* Logs from Charles or some other proxy to see if the data is being sent to New Relic
* `package.json` 
* A sample app that can reproduce the issue

**Comment by sthota-fms** [comment]
I am on RN 0.71.6 (which comes with flipper and Hermes turned on as a default config)and updated newrelic-react-native-agent to 1.1.0 with android agent at 6.10.0. I am getting the following error in DEV mode; maybe because the flipper is turned on? 

![image](https://user-images.githubusercontent.com/121507008/230269794-799409ed-999b-4add-9148-7849748711b5.png)

Here's the error I get in the console:
![image](https://user-images.githubusercontent.com/121507008/230269858-cbfe5ee1-19c2-4963-9fe6-75902aa7771d.png)

Please assist me with this issue. I had to disable NewRelic to make the app run normally in DEV mode.
![image](https://user-images.githubusercontent.com/121507008/230270007-465a8404-28f5-40b2-8942-ba7b4d838816.png)

**Comment by kthai-nr** [comment]
@sthota-fms Hello, I've tested our agent v1.1.0 with an app on react-native 0.71.6 and I haven't been able to reproduce this issue. I have Hermes, Flipper, and DEV mode enabled. Do these problems still occur when DEV mode is off or if hermes is disabled? Can you run `npx react-native info` and print the output here so we can make sure there isn't any conflicts with versions? If possible, more details on how to recreate this issue would be helpful for us to diagnose the root cause.
